<a href="https://colab.research.google.com/github/Tranminhtuan48/pythonbasics/blob/main/BaiTap_NumPy_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Câu 1: Sử dụng thư viện Numpy, hãy tạo một vector a có 7 chiều (tương ứng 7 phần tử) với giá
trị các phần tử được sinh bằng hàm (kết quả xuất ra màn hình):
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()

In [9]:
def infor(vec_x):
  print("Vector x: ",vec_x)
  print("Số chiều của x: ", vec_x.ndim)
  print("Kích thước của x: ", vec_x.shape)
  print("Vector chuyển vị của x: \n", vec_x.T)
  print("Số chiều của vector chuyển vị của x: ", (vec_x.T).ndim)
  print("Kích thước của chuyển vị của x: ", vec_x.T.shape)

In [10]:
#np.arange():
vec_a = np.arange(0,7,1)
infor(vec_a)
#np.linspace():
vec_b = np.linspace(0,10,num = 7)
infor(vec_b)
#np.logspace():
vec_c = np.logspace(1,2, num = 7)
infor(vec_c)
#np.random.rand():
vec_d = np.random.rand(7)
infor(vec_d)

Vector x:  [0 1 2 3 4 5 6]
Số chiều của x:  1
Kích thước của x:  (7,)
Vector chuyển vị của x: 
 [0 1 2 3 4 5 6]
Số chiều của vector chuyển vị của x:  1
Kích thước của chuyển vị của x:  (7,)
Vector x:  [ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]
Số chiều của x:  1
Kích thước của x:  (7,)
Vector chuyển vị của x: 
 [ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]
Số chiều của vector chuyển vị của x:  1
Kích thước của chuyển vị của x:  (7,)
Vector x:  [ 10.          14.67799268  21.5443469   31.6227766   46.41588834
  68.12920691 100.        ]
Số chiều của x:  1
Kích thước của x:  (7,)
Vector chuyển vị của x: 
 [ 10.          14.67799268  21.5443469   31.6227766   46.41588834
  68.12920691 100.        ]
Số chiều của vector chuyển vị của x:  1
Kích thước của chuyển vị của x:  (7,)
Vector x:  [0.83888905 0.83655119 0.22457301 0.20148113 0.89136374 0.50913822
 0.705051  ]
Số chiều của x:  1
Kích thước của x:  (7,

Câu 2: Sử dụng thư viện Numpy, hãy tạo ra ma trận A10x7 với giá trị các phần tử của ma trận A
được sinh bởi:
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()

In [16]:
def OpR(matrix_x):
  print("Ma trận x: \n", matrix_x)
  print("Số chiều của x: ", matrix_x.ndim)
  print("Ma trận chuyển vị của x: \n", matrix_x.T)
  print("Số chiều của chuyển vị của x: ", (matrix_x.T).ndim)
  print("Kích thước của chuyển vị của x: ", (matrix_x.T).shape)

In [18]:
#np.arrange()
matrix_x = np.arange(0,70,1).reshape(10,7)
OpR(matrix_x)

Ma trận x: 
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
Số chiều của x:  2
Ma trận chuyển vị của x: 
 [[ 0  7 14 21 28 35 42 49 56 63]
 [ 1  8 15 22 29 36 43 50 57 64]
 [ 2  9 16 23 30 37 44 51 58 65]
 [ 3 10 17 24 31 38 45 52 59 66]
 [ 4 11 18 25 32 39 46 53 60 67]
 [ 5 12 19 26 33 40 47 54 61 68]
 [ 6 13 20 27 34 41 48 55 62 69]]
Số chiều của chuyển vị của x:  2
Kích thước của chuyển vị của x:  (7, 10)


In [19]:
#np.linspace():
matrix_x = np.linspace((1,1,1,1,1,1,1),(100,100,100,100,100,100,100),10)
OpR(matrix_x)

Ma trận x: 
 [[  1.   1.   1.   1.   1.   1.   1.]
 [ 12.  12.  12.  12.  12.  12.  12.]
 [ 23.  23.  23.  23.  23.  23.  23.]
 [ 34.  34.  34.  34.  34.  34.  34.]
 [ 45.  45.  45.  45.  45.  45.  45.]
 [ 56.  56.  56.  56.  56.  56.  56.]
 [ 67.  67.  67.  67.  67.  67.  67.]
 [ 78.  78.  78.  78.  78.  78.  78.]
 [ 89.  89.  89.  89.  89.  89.  89.]
 [100. 100. 100. 100. 100. 100. 100.]]
Số chiều của x:  2
Ma trận chuyển vị của x: 
 [[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]]
Số chiều của chuyển vị của x:  2
Kích thước của chuyển vị của x:  (7, 10)


In [20]:
#np.logspace():
matrix_x = np.logspace((1,1,1,1,1,1,1),(3,3,3,3,3,3,3),10)
OpR(matrix_x)

Ma trận x: 
 [[  10.           10.           10.           10.           10.
    10.           10.        ]
 [  16.68100537   16.68100537   16.68100537   16.68100537   16.68100537
    16.68100537   16.68100537]
 [  27.82559402   27.82559402   27.82559402   27.82559402   27.82559402
    27.82559402   27.82559402]
 [  46.41588834   46.41588834   46.41588834   46.41588834   46.41588834
    46.41588834   46.41588834]
 [  77.42636827   77.42636827   77.42636827   77.42636827   77.42636827
    77.42636827   77.42636827]
 [ 129.1549665   129.1549665   129.1549665   129.1549665   129.1549665
   129.1549665   129.1549665 ]
 [ 215.443469    215.443469    215.443469    215.443469    215.443469
   215.443469    215.443469  ]
 [ 359.38136638  359.38136638  359.38136638  359.38136638  359.38136638
   359.38136638  359.38136638]
 [ 599.48425032  599.48425032  599.48425032  599.48425032  599.48425032
   599.48425032  599.48425032]
 [1000.         1000.         1000.         1000.         1000.
  1000.

In [21]:
#np.random.rand():
matrix_x = np.random.rand(10,7)
OpR(matrix_x)

Ma trận x: 
 [[0.22852741 0.65673144 0.21427114 0.98486847 0.55879472 0.60619431
  0.19217759]
 [0.52428241 0.52614465 0.48482935 0.72724616 0.06047136 0.04109349
  0.24251934]
 [0.25758141 0.76574729 0.15169762 0.76096141 0.20938331 0.48930517
  0.73898347]
 [0.80305507 0.08478917 0.09204333 0.54234646 0.14358417 0.40677822
  0.99920773]
 [0.36990384 0.15604388 0.89391279 0.44789944 0.78837964 0.25731204
  0.62963184]
 [0.46777169 0.98850888 0.33764373 0.42737078 0.63759566 0.41897088
  0.01683371]
 [0.17226732 0.18518075 0.15745943 0.94347836 0.4753283  0.63485061
  0.73550129]
 [0.9927542  0.61788579 0.8505687  0.20788616 0.31560062 0.71770757
  0.01091693]
 [0.25452567 0.6696995  0.16555032 0.33737231 0.80384723 0.32256674
  0.7965515 ]
 [0.30629337 0.12346459 0.0706551  0.21021511 0.47279398 0.13540944
  0.09202294]]
Số chiều của x:  2
Ma trận chuyển vị của x: 
 [[0.22852741 0.52428241 0.25758141 0.80305507 0.36990384 0.46777169
  0.17226732 0.9927542  0.25452567 0.30629337]
 [0.6

Câu 3: Sử dụng thư viện Numpy, hãy:
- Chuyển ma trận A ở câu 2 thành vector. (Gợi ý: sử dụng hàm flatten())

- Chuyển vector vừa được tạo ra ở câu trên thành ma trận. (Gợi ý: sử dụng hàm reshape())

In [29]:
matrix_b = np.arange(0,70,1).reshape(10,7)
vector_c = matrix_b.flatten()
print(vector_c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [30]:
matrix_d = vector_c.reshape(10,7)
print(matrix_d)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]


Câu 4:Sử dụng thư viện Numpy, hãy:
- Tạo ra 1 ma trận A10x15 với các giá trị được sinh ra bởi hàm logspace();

- Hãy trích rút dòng thứ 3 của ma trận A (tương ứng với 1 vector hàng);

- Hãy trích rút ra cột thứ 5 của ma trận A (tương ứng với 1 vector cột).

In [37]:
matrix_e = np.logspace(0,3,150).reshape(10,15)
print(matrix_e)
print("row_vec")
row_vec = matrix_e[2, :] 
print(row_vec)
print("col_vec")
col_vec = matrix_e[:, 4]
print(col_vec)

[[   1.            1.04745224    1.09715619    1.1492187     1.2037517
     1.26087241    1.32070362    1.38337396    1.44901815    1.5177773
     1.58979923    1.66523876    1.74425806    1.827027      1.91372352]
 [   2.00453398    2.0996536     2.19928686    2.30364794    2.41296118
     2.52746159    2.64739529    2.77302012    2.90460612    3.04243618
     3.18680658    3.33802767    3.49642455    3.66233771    3.83612383]
 [   4.01815648    4.20882699    4.40854524    4.61774057    4.83686269
     5.06638264    5.30679382    5.55861305    5.82238167    6.0986667
     6.38806207    6.6911899     7.00870182    7.3412804     7.68964057]
 [   8.05453121    8.43673672    8.83707874    9.25641789    9.69565562
    10.15573615   10.63764854   11.14242875   11.67116191   12.22498464
    12.8050875    13.41271753   14.04918097   14.71584602   15.41414582]
 [  16.1455815    16.91172545   17.71422463   18.5548042    19.43527115
    20.35751822   21.32352798   22.33537706   23.39524065   24.

Câu 5: Thực hiện các yêu cầu sau:

In [47]:
#Ham tinh trung binh
def means(vec_a):
  s = 0
  for i in vec_a:
    s += i
  return s/len(vec_a)

In [48]:
#Ham tinh trung vi
def median(vec_a):
  len_a = len(vec_a)
  # Sap xep phan tu tang dan:
  for i in range(len_a - 1):
    for j in range(i + 1, len_a):
      if (vec_a[i] > vec_a[j]):
        vec_a[i],vec_a[j] = vec_a[j], vec_a[i]
  # tinh trung vi:
  if (len_a % 2 != 0):
    return vec_a[int(len_a / 2)]
  else:
    return ((vec_a[int((len_a-1)/2)]) + (vec_a[int((len_a-1)/2) + 1])) / 2

In [55]:
#Ham tinh yeu vi
def mode(vec_a):
    result = []
    # tan suat phan tu trong vec_a:
    tan_so = {}
    for i in vec_a:
        if i in tan_so:
            tan_so[i] += 1
        else:
            tan_so[i] = 1
    
    # tinh tan so lon nhat:
    max_tan_so = 0
    for i in tan_so.values():
        if i >= max_tan_so:
            max_tan_so = i
    
    # Tìm số yếu vị:
    for i in tan_so:
        if tan_so[i] == max_tan_so:
            result.append(i)
    return result

- Xây dựng hàm tính phương sai:

In [57]:
#ham tinh phuong sai
def variance(vec_a):
  mean_a = means(vec_a)
  s = 0
  for i in vec_a:
    s += (i - mean_a) ** 2
  return s/(len(vec_a))

In [51]:
#ham tinh do lech chuan
def sd(vec_a):
  return variance(vec_a) ** 0.5

- Hãy tạo ra ma trận A15x10 với các giá trị sinh bởi hàm arrange():

In [52]:
A = np.arange(1,151,1).reshape(15,10)
print(A)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]]


- Áp dụng 5 hàm ở trên cho từng hàng của ma trận A

In [59]:
#Trung binh
print("Trung binh")
np.apply_along_axis(means, 1, A)

Trung binh


array([  5.5,  15.5,  25.5,  35.5,  45.5,  55.5,  65.5,  75.5,  85.5,
        95.5, 105.5, 115.5, 125.5, 135.5, 145.5])

In [60]:
#Trung vi
print("Trung vi")
np.apply_along_axis(median, 1, A)

Trung vi


array([  5.5,  15.5,  25.5,  35.5,  45.5,  55.5,  65.5,  75.5,  85.5,
        95.5, 105.5, 115.5, 125.5, 135.5, 145.5])

In [61]:
#Yeu vi
print("Yeu vi")
np.apply_along_axis(mode, 1, A)

Yeu vi


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150]])

In [62]:
#Phuong sai
print("Phuong sai")
np.apply_along_axis(variance, 1, A)

Phuong sai


array([8.25, 8.25, 8.25, 8.25, 8.25, 8.25, 8.25, 8.25, 8.25, 8.25, 8.25,
       8.25, 8.25, 8.25, 8.25])

In [63]:
#Do lech chuan
print("Do lech chuan")
np.apply_along_axis(sd, 1, A)

Do lech chuan


array([2.87228132, 2.87228132, 2.87228132, 2.87228132, 2.87228132,
       2.87228132, 2.87228132, 2.87228132, 2.87228132, 2.87228132,
       2.87228132, 2.87228132, 2.87228132, 2.87228132, 2.87228132])

- Áp dụng 5 hàm ở trên cho từng cột của ma trận A:

In [64]:
#Trung binh
np.apply_along_axis(means, 0, A)

array([71., 72., 73., 74., 75., 76., 77., 78., 79., 80.])

In [65]:
#Trung vi
np.apply_along_axis(median, 0, A)

array([71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [66]:
#Yeu vi
np.apply_along_axis(mode, 0, A)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150]])

In [67]:
#Phuong sai
np.apply_along_axis(variance, 0, A)

array([1866.66666667, 1866.66666667, 1866.66666667, 1866.66666667,
       1866.66666667, 1866.66666667, 1866.66666667, 1866.66666667,
       1866.66666667, 1866.66666667])

In [68]:
#Do lech chuan
np.apply_along_axis(sd, 0, A)

array([43.20493799, 43.20493799, 43.20493799, 43.20493799, 43.20493799,
       43.20493799, 43.20493799, 43.20493799, 43.20493799, 43.20493799])