<a href="https://colab.research.google.com/github/Tranminhtuan48/pythonbasics/blob/main/BaiTapNumpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Xét không gian $R$3, một điểm A trong không gian này có tọa độ là (5, 7, 14). Hãy khởi tạo giá trị của điểm A nêu trên bằng Numpy.

In [1]:
import numpy as np
import math

In [4]:
a = np.array([[5],[7],[14]])
print(a)

[[ 5]
 [ 7]
 [14]]


2.Mở rộng không gian lên R15, điểm A trong không gian này có tọa độ là (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15). Hãy khởi tạo điểm A trong không gian 15 chiều này bằng Numpy.

In [9]:
b = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
2


3. Trong không gian Rn, xét vector OA với O là điểm gốc tọa độ và A là điểm có tọa độ tổng quát là (a1, a2, ..., an). Vector OA lúc này được viết dưới dạng vector cột (column vector). Hãy viết chương trình sinh ngẫu nhiên một vector trong không gian Rn với n là số nguyên dương được nhập vào từ bàn phím. Yêu cầu: sử dụng Numpy.

In [73]:
# Kiem tra n nguyen duong
def so_nguyen_duong(num):
  if (int(num)>0):
    return True
  else:
    return False
#Ham random vector
def random_vector(num):
  n = input("Nhap vao so nguyen: ")
  while not so_nguyen_duong(n):
    n = input("Nhap vao so nguyen: ")
  n = int(n)
  c = [np.random.randint(0,10,n)]
  return c

In [57]:
d = random_vector(1)[0]
print(d)

Nhap vao so nguyen: 5
[[9]
 [3]
 [6]
 [0]
 [8]]


4. Trong không gian R3, xét vector OA:

Hãy viết chương trình tính chiều dài của vector OA, biết công thức tổng quát để tính chiều dài vector OA trong không gian Rn là:

In [18]:
e = np.array([[7],[-5],[8]])
lenght_e = np.linalg.norm(e)
print(lenght_e)

11.74734012447073


5. Trong không gian Rn, hãy sinh ngẫu nhiên 2 điểm A và B. Xác định vector AB và tính chiều dài của vector này ‖AB‖.

In [32]:
f,g = random_vector(2)
print("A:", f); print("B:", g)
h = g - f #AB
print("AB:", h)
#lenght_AB
Lenght_AB = np.linalg.norm(h)
print("Do dai vector AB: ", Lenght_AB)

Nhap vao so nguyen: 5
A: [[9]
 [9]
 [5]
 [2]
 [1]]
B: [[0]
 [1]
 [7]
 [7]
 [8]]
AB: [[-9]
 [-8]
 [ 2]
 [ 5]
 [ 7]]
Do dai vector AB:  14.933184523068078


6. Tích vô hướng của 2 vector a & b (dot product hoặc inner product hoặc scalar product) được tính theo công thức tổng quát. Trong không gian Rn, hãy sinh ngẫu nhiên 2 vector a & b và tính tích vô hướng của 2 vector này.

In [62]:
i,k = random_vector(2)
print("a:",i); print("b:",k)
l = np.inner(i,k)
print("Tichs vo huong:", l)

Nhap vao so nguyen: 4
Nhap vao so nguyen: 4
a: [5 7 0 6]
b: [2 8 1 8]
Tichs vo huong: 114


7. Tích hữu hướng (cross product) của 2 vector a & b được tính theo công thức tổng quát. Trong không gian Rn, hãy sinh ngẫu nhiên 2 vector a & b và tính tích hữu hướng của 2 vector này.

In [ ]:
m = random_vector(1)
n = random_vector(1)
print("a:",m); print("b:",n)
o = np.cross(n,m)
print("Tichs vo huong:", o)

8. Phép chuyển vị (transpose): trong numpy, một vector a khi thực hiện chuyển vị sẽ được thực hiện thông qua thao tác a.T

Hãy viết chương trình sinh ngẫu nhiên một vector a trong không gian Rn, số nguyên dương n được nhập vào từ bàn phím. Xuất ra màn hình giá của vector a và chuyển vị của vector a .

In [74]:
a = random_vector(1)[0]
print("a: ", a)
print("Phep chuyen vi a: ", a.T)

Nhap vao so nguyen: 4
a:  [[1]
 [1]
 [4]
 [7]]
Phep chuyen vi a:  [[1 1 4 7]]


9. Xét 2 cấu trúc list dưới đây:
  1. a = [1, 2, 3, 4, 5]
  2. b = [[1], [2], [3], [4], [5]]

  Hãy:
- Xuất a và b ra màn hình
- Tạo vector tương ứng từ a và b, xuất kết quả ra màn hình
- Thực hiện phép chuyển vị đối với 2 vector ở trên và xuất kết quả ra màn hình.

In [77]:
a = [1, 2, 3, 4, 5]
b = [[1], [2], [3], [4], [5]]

print("a: ",a)
print("b: ", b)
Vector_a = np.array(a)
Vector_b = np.array(b)
print("Vector_a:", Vector_a)
print("Vector_b: \n", Vector_b)
print("Vec_chuyenvi_a", Vector_a.T)
print("Vec_chuyenvi_b", Vector_b.T)

a:  [1, 2, 3, 4, 5]
b:  [[1], [2], [3], [4], [5]]
Vector_a: [1 2 3 4 5]
Vector_b: 
 [[1]
 [2]
 [3]
 [4]
 [5]]
Vec_chuyenvi_a [1 2 3 4 5]
Vec_chuyenvi_b [[1 2 3 4 5]]


10. Trong không gian R, hãy sinh ngẫu nhiên vector a và b⃗ , n là số nguyên dương nhập vào từ bàn phím. Hãy:
- Thực hiện phép nhân: ma với m là số bất kỳ, xuất kết quả ra màn hình
- Thực hiện phép cộng 2 vector: a + b⃗ và xuất kết quả ra màn hình.

In [81]:
a,b = random_vector(2)
print("Vector_a: \n", a)
print("Vector_b: \n", b)
c = float(input("nhap so:"))
print(f"a* m = \n", a*c)
print("a+b= \n", a+b)

Nhap vao so nguyen: 3
Vector_a: 
 [[6]
 [9]
 [7]]
Vector_b: 
 [[0]
 [2]
 [0]]
nhap so:5
a* m = 
 [[30.]
 [45.]
 [35.]]
a+b= 
 [[ 6]
 [11]
 [ 7]]
