<a href="https://colab.research.google.com/github/Tranminhtuan48/pythonbasics/blob/main/BaiTap_NumPy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Hãy trình bày cú pháp của hàm apply_along_axis() và ý nghĩa của từng tham số của hàm
này.

cu phap

numpy.apply_along_axis (func1d,axis,arr,args,*kwargs)

y nghia

func1d: Hamm nay chap mhan mang 1-D.No ap dung cho cac lat arr 1-D doc theo truc duoc chi dinh

axis: Truc doc theo arr duoc cat

arr: Mang dau vao

kwargs: Cac doi so duoc bo sung cho func1d

# Ham tra ve: mot mang co hinh dang giong mang dua vao, ngoai tru cac tru duoc thay the bang cac gia tri moi bang cac gia tri tra ve cua func1d

2.Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [1]:
import numpy as np

In [2]:
A = np.random.randint(0,30, (15,17))
print(A)

[[17 20 29 24 26 11 13  4 20 11  9 24 26 27 22 21 17]
 [ 8 10 20  5 20 19 23 22 28 17 19  9 28 29  8  2 14]
 [ 1 24  3 20 20 15  5 14 10 17 27  2  3  3 16  3  2]
 [ 2 22 14 10 21 21 28 10 28  1  0 20  8 29 14  3 12]
 [20 22 12 11  0  4  1  1 27 13 11  4 22  3 18 28  0]
 [ 5  8 25 15  6  1 24 13 14 25 26  7 22 19 20 22  5]
 [27 15 24 15 15 13  5  2 19  1 18 19  6 19 15 24 12]
 [ 2  2 28 17 23 17 26 17  6 12 19 14  7  8 16 28 14]
 [ 2 15  7  7 26 26  3  7 10  5 17 22  4 18 29  8  7]
 [ 7 28 16 10 16  9 27 24 12  8 17 27 28  7 18  4 18]
 [ 4 20 20 29  7 17  9 26 16  5 10  4 14 25 10  3 20]
 [21 17  9 22 19 13 25  4 24  8 25  5 10 22  5  0 11]
 [ 8  5  3 22  6  4  1  4 22 22 24 15 22 23 16 26  8]
 [22 14 21 21 12 26 29 23 11 28 11  1 27  5  9 24 12]
 [12 13 25 15  9 24  6 10 23 16 15 10 13  7 22 15  0]]


3.Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [3]:
def GTLN(vec_a):
  return np.max(vec_a)
print("GTLN: \n", np.apply_along_axis(GTLN, 1,A))

GTLN: 
 [29 29 27 29 28 26 27 28 29 28 29 25 26 29 25]


4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [4]:
def GTNN(vec_b):
  return np.min(vec_b)
print("GTNN: \n", np.apply_along_axis(GTNN, 0,A))

GTNN: 
 [1 2 3 5 0 1 1 1 6 1 0 1 3 3 5 0 0]


5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [5]:
def Tong(vec_c):
  return np.sum(vec_c)
print("Tong: \n", np.apply_along_axis(Tong, 1,A))

Tong: 
 [321 281 185 243 197 257 249 256 213 276 239 240 231 296 235]


6: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong_2(vector_a) có tham số đầu vào là
1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp
dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng
hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.

In [6]:
def TongCong(vec_d):
  s = 0
  for i in range(len(vec_d)):
    if (i % 2 !=0):
      s += vec_d[i]
  return s
print("list tong gia tri le cua hang: \n", np.apply_along_axis(TongCong, 1,A))

list tong gia tri le cua hang: 
 [142 113  98 116  86 110 108 115 108 117 129  91 121 142 110]
