<a href="https://colab.research.google.com/github/Tranminhtuan48/pythonbasics/blob/main/BaiTap_NumPy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Hãy trình bày cú pháp của hàm apply_along_axis() và ý nghĩa của từng tham số của hàm
này.

cu phap

numpy.apply_along_axis (func1d,axis,arr,args,*kwargs)

y nghia

func1d: Hamm nay chap mhan mang 1-D.No ap dung cho cac lat arr 1-D doc theo truc duoc chi dinh

axis: Truc doc theo arr duoc cat

arr: Mang dau vao

kwargs: Cac doi so duoc bo sung cho func1d

# Ham tra ve: mot mang co hinh dang giong mang dua vao, ngoai tru cac tru duoc thay the bang cac gia tri moi bang cac gia tri tra ve cua func1d

2.Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [1]:
import numpy as np

In [2]:
A = np.random.randint(0,30, (15,17))
print(A)

[[ 8 13 19  6 21  3 29 29  1 29  8 12  8 17 17 26 13]
 [27 27 28  4 18 23 27 12 17  0 18  6 12 29 17  8  5]
 [ 3  4  1 26 20  3 18 13 12 24  9  0  6 27 13  0 13]
 [26  2 12 20 20 10 26 10 15 25 25  4 20 13 20  5 22]
 [ 9 28 14  6 23  2 21 25 29 28  8 11 26 20 19  1 24]
 [17 17  7 27 11 27 13 10 22  0 11 22 19  4  4 23 13]
 [22 28 11 20 27 11  9  2 14 20  4 13  6  6 25 14 10]
 [13  2 21  0  3  2 15 21 27 10 24 28 21  6 12 28 11]
 [ 9 22 13 22 24  4  1  7 21 20  6 13 29 20 28  0 29]
 [29 25 23 29 23 19 14  9 21  9 22  6  7 10  4 15 23]
 [24 26  5  6 12 13  1 13  4 15  8  5  4  9 28  8  1]
 [10  6 13 24  7 25 27  7 13 25 29 14 22  3 20  3  5]
 [12 19  5 25 26 15  1 21  0 29 10 18 29 15  6  1  4]
 [20 24 12 27  4  0 27  7 20  9  2  3 15  9 17 26  9]
 [19 18 26 12  5 22  3 24 15 28  4 29 10  5  7 26 12]]


3.Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def GTLN(vec_a):
  return np.max(vec_a)
print("GTLN: \n", np.apply_along_axis(GTLN, 1,A))

Tap GTLN cua hang: 
 [18 19 19 18 17 19 17 19 16 17 19 17 19 19 15]


4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def GTNN(vec_b):
  return np.min(vec_b)
print("GTNN: \n", np.apply_along_axis(GTNN, 0,A))

Tap GTNN cua hang: 
 [0 0 3 4 1 1 3 0 1 0 2 0 0 0 1 0 0]


5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def Tong(vec_c):
  return np.sum(vec_c)
print("Tong: \n", np.apply_along_axis(Tong, 1,A))

Tap Tong cua hang: 
 [190 186 175 157 133 176 176 203 145 137 164 101 180 208 144]


6: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong_2(vector_a) có tham số đầu vào là
1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp
dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng
hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.

In [ ]:
def TongCong(vec_d):
  s = 0
  for i in range(len(vec_d)):
    if (i % 2 !=0):
      s += vec_d[i]
  return s
print("list tong gia tri le cua hang: \n", np.apply_along_axis(TongCong, 1,A))

Tap cac tong gtri cos index le cua hang: 
 [ 85 105  92  88  49  69  71  89  77  54  72  41  83  85  71]
