<a href="https://colab.research.google.com/github/Tranminhtuan48/pythonbasics/blob/main/BaiTap_NumPy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Bài 1:Trong Toán học, ma trận (matrix) là một mảng 2 chiều chứa số hoặc các đối
tượng toán học khác. Một cách tổng quát ma trận A có m hàng và n cột chứa các số thực, ký hiệu là A ∈ Rm×n hay Am×n hay A = (ai,j)
m×n 

Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ R7×5, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [2]:
a = np.random.randint(0,30, (7,5))
print(a)

[[23  5  6 27 20]
 [11  1  3 27  2]
 [ 0 26  1 27  8]
 [23  6 16 18 22]
 [24 13 27 12  8]
 [ 1  9 26  9 28]
 [ 7 11 23  5  5]]


Bài 2: Ma trận Am×n được gọi là ma trận không khi ai,j = 0, ∀i,j. Sử dụng thư viện NumPy, hãy tạo một ma trận 0 - A6×7.

In [3]:
b = np.zeros((6,7))
print(b)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Bài 3: Là ma trận có số hàng và số cột bằng nhau. Sử dụng thư viện NumPy,
hãy tạo ra một ma trận A ∈ R7×7, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [7]:
c = np.random.randint(0,30, (7,7))
print(c)

[[23 14 28  7 28 18 14]
 [29  8 11 22 27 22 16]
 [28 24 17 17 26 23 26]
 [ 3 20 12  5  8 12 14]
 [15 19 22 27 20 10 22]
 [26 19 11 27  6  0 11]
 [ 1  2 11 26 29 25  2]]


Bài 4: Ma trận vuông có các phần tử trên đường chéo ai,i ≠ 0
trong khi các phần tử còn lại ai,j = 0, ∀i ≠ j.


Sử dụng thư viện NumPy, hãy tạo một ma trận chéo A6×6 với phần tử nằm trên đường chéo có giá trị là 15.

In [5]:
d = np.zeros([6,6], dtype = int)
np.fill_diagonal(d, 15)
print(d)

[[15  0  0  0  0  0]
 [ 0 15  0  0  0  0]
 [ 0  0 15  0  0  0]
 [ 0  0  0 15  0  0]
 [ 0  0  0  0 15  0]
 [ 0  0  0  0  0 15]]


Bài 5: Sử dụng thư viện NumPy, hãy tạo một ma trận tam giác trên A8×8.

In [6]:
e = np.triu(np.random.randint(0,30,[8,8]))
print(e)

[[10  0  4 23 19 29 21 20]
 [ 0 23 20 27 26 12  0  6]
 [ 0  0 29  9  3 19 27 12]
 [ 0  0  0 14 28 16  9 13]
 [ 0  0  0  0 12 24 23 27]
 [ 0  0  0  0  0  9 24 28]
 [ 0  0  0  0  0  0 12  7]
 [ 0  0  0  0  0  0  0 10]]


Bài 6: Tương tự bài 5, hãy xây dựng
ma trận tam giác dưới. Kết quả xuất ra màn hình.

In [8]:
f = np.tril(np.random.randint(1,30,[8,8]), k = 0)
print(f)

[[18  0  0  0  0  0  0  0]
 [10 15  0  0  0  0  0  0]
 [15  4 20  0  0  0  0  0]
 [ 7  2 15 11  0  0  0  0]
 [16  8  6 29 24  0  0  0]
 [16  1 18  4 13  5  0  0]
 [27 22  8 25 28 21 28  0]
 [ 5 20  4 22  6 21 27  3]]


Bài 7: Ma trận đơn vị In có số chiều n là một ma trận vuông mà mọi phần tử trên đường chéo chính bằng 1. Sử dụng thư viện NumPy, hãy tạo ra một ma trận I9. Kết quả xuất ra màn hình.

In [ ]:
g = np.identity(9, dtype = int)
print(g)

[[1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1]]


Bài 8: Phép toán trên ma trận:

* Phép cộng ma trận:

In [10]:
# create matrix h
h = np.random.randint(0,30, [6,7])
print("Matrix h : \n",h)

# create matrix i
i = np.random.randint(0,30, [6,7])
print("Matrix i: \n",i)

# Sum two Matrixs
print("h + i = \n", h + i)

Matrix h : 
 [[28 12 15 16 16 26 17]
 [24  9 27 12  3  2  1]
 [12  0 19 14 12  8  8]
 [18 19 14 29  6 20 20]
 [24  8  7  3  8 20  6]
 [ 4  1 19  1 21  3  3]]
Matrix i: 
 [[ 7  2  5 26 13  1  8]
 [12 10 19 24  4 12  9]
 [ 1 18 15 17 13 16  0]
 [16 15 13 11  5 10 20]
 [29 27 29  4  9  6  3]
 [ 8  9 24 21  2  1 24]]
h + i = 
 [[35 14 20 42 29 27 25]
 [36 19 46 36  7 14 10]
 [13 18 34 31 25 24  8]
 [34 34 27 40 11 30 40]
 [53 35 36  7 17 26  9]
 [12 10 43 22 23  4 27]]


* Phép nhân vô hướng một số với ma trận: 

In [14]:
# create matrix k
k = np.random.randint(0,30, [6,7])
print("Ma trận A: \n",A)

# scalar multiplication
l = float(input("Input num: "))
print(f"k * {l}: \n", k * l)

Ma trận A: 
 [[24  5 25 26 24  1  8]
 [11  3  7  7 28 22 12]
 [18  5 25 15  8 21  0]
 [13 18  7  8  8 29 10]
 [24  6 20  9  3 26  6]
 [ 5 16 29  3  2  4  9]]
Input num: 3
k * 3.0: 
 [[63.  0. 36. 63. 33. 30. 66.]
 [15. 33. 48. 60. 66.  3. 63.]
 [84. 57.  6. 69. 84. 57. 15.]
 [66. 63.  0. 42. 39. 12. 78.]
 [18. 24.  3. 12. 54. 84. 72.]
 [ 3.  3. 66. 60. 24. 51. 21.]]


* Phép chuyển vị ma trận: Sinh ngẫu nhiên một ma trận có kích thước 3x7. Thực hiện phép
chuyển vị đối với ma trận này. Xuất các ma trận này ra màn hình.

In [15]:
# create matrix m 3x7
m = np.random.randint(0,30, [3,7])
print("Matrix m: \n",m)

# transposition
print("transposition: \n",m.T)

Matrix m: 
 [[ 9 27 22 15 21 15  4]
 [12  7  5  8  3  0  5]
 [23 24 19 13 11  4 13]]
transposition: 
 [[ 9 12 23]
 [27  7 24]
 [22  5 19]
 [15  8 13]
 [21  3 11]
 [15  0  4]
 [ 4  5 13]]


* Phép nhân 2 ma trận: Am×n ∙ Bn×p = Cm×p. Hãy sinh ngẫu nhiên 2 ma trận A5×7 và B7×3, tiến hành nhân 2 ma trận này để thu được ma trận C5×3. Xuất các ma trận trên ra màn hình.

In [16]:
# create matrix n 5x7
n = np.random.randint(0,30, [5,7])
print("Matrix n: \n",n)

# create matrix o 7x3
o = np.random.randint(0,30, [7,3])
print("Matrix o: \n",o)

#Result
print("Matrix p: \n",n.dot(o))


Matrix n: 
 [[18 10  9 18 27 24 23]
 [ 4  3 12 27  8  0 23]
 [ 8 18 28 19 28 12 20]
 [20  8 21 11  6 15  5]
 [25 21  7  7 10  3 22]]
Matrix o: 
 [[ 2 19  6]
 [10  4  1]
 [25 23 15]
 [27 19  0]
 [11 13  5]
 [12 10 21]
 [26  7  3]]
Matrix p: 
 [[2030 1683  961]
 [1753 1142  316]
 [2381 1853  938]
 [1318 1367  803]
 [1342 1167  455]]


* Ma trận khả nghịch: ma trận vuông An×n gọi là khả nghịch (hay không suy biến) nếu tồn tại một ma trận vuông Bn×n sao cho A ∙ B = In . Khi này, B được gọi là ma trận nghịch đảo của A và ký hiệu là A mũ -1. Cho ma trận A5×7, hãy tính ma trận khả nghịch của A.

In [17]:
q = np.random.randint(0,30, [7,7])
print("Matrix q: \n",q)

# determinant:
det_q = np.linalg.det(q)

# inverse matrix
if (det_q != 0):
  print("inverse matrix of q:\n",np.linalg.inv(q))
else:
  print("q not have inverse matrix")


Matrix q: 
 [[11 24  7  6 17  2  6]
 [16 21 17  1  9 18 16]
 [19 22 19 26  7 28  7]
 [26  3 17 11 28 12 24]
 [ 6 22 13 11 14  9  1]
 [ 0 21 13 22 12  3 25]
 [ 7 20 27 12 19 18 29]]
inverse matrix of q:
 [[-0.25523342  0.21531684 -0.09691603  0.09331761  0.25049265  0.1368938
  -0.246473  ]
 [ 0.05708625  0.00209374  0.00971292 -0.02830586 -0.0324947  -0.00336042
   0.01213234]
 [-0.64292357  0.41998245 -0.25464423  0.16550036  0.66322899  0.2837431
  -0.44167183]
 [-0.05367995  0.00229152  0.00500688  0.01964255  0.04917837  0.04670883
  -0.04958459]
 [ 0.32674823 -0.25370617  0.11185114 -0.06781203 -0.28837295 -0.17452669
   0.26189242]
 [ 0.50368767 -0.35705725  0.2242155  -0.14733807 -0.52830502 -0.27527733
   0.41612529]
 [ 0.11632449 -0.05754032  0.03925568 -0.02933836 -0.15904487 -0.02902134
   0.08746922]]


Bài 9: Sử dụng numpy để thực hiện các yêu cầu sau
* Vector hàng (row vector) thực chất là ma trận có kích thước 1 × n. Hãy tạo ngẫu nhiên 1 vector hàng - x có kích thước 1 × 8. Kết quả xuất ra màn hình.
* Vector cột (column vector) thực chất là ma trận có kích thước m × 1. Hãy tạo ngẫu nhiên 1 vector cột – x có kích thước 8 × 1. Kết quả xuất ra màn hình.

In [18]:
# Create row vector
row_vec = np.random.randint(0,30, (1,8))
print("Row Vector: \n", row_vec)

# Create column vector
column_vec = np.random.randint(0,30, (8,1))
print("Column Vector: \n", column_vec)

Row Vector: 
 [[16 28  1 15 22  4 28 15]]
Column Vector: 
 [[15]
 [10]
 [ 7]
 [13]
 [ 1]
 [11]
 [16]
 [28]]


Bài 10: Xây dựng chương trình Python sử dụng thư viện NumPy để giải hệ phương trình tuyến tính có dạng: Am×n ∙ xn×1 = bm×1

In [19]:
m = int(input("equation : "))
n = int(input("Hidden num: "))
index_list = []
value_list = []
 
for i in range(m):
    print(f"-------Phương trình {i+1}------")
    for y in range(n):
        temp1 = float(input(f"x[{i+1}][{y+1}] = "))
        index_list.append(temp1)
    temp2 = float(input(f"b[{i+1}] = "))
    value_list.append(temp2)

a = np.array(index_list).reshape((m,n))
b = np.array(value_list).reshape((m,1))

# Coefficient Matrix:
a1 = np.concatenate((a,b), axis = 1)

if (np.linalg.matrix_rank(a) < np.linalg.matrix_rank(a1)):
    print("System of equations with no solution")
elif (np.linalg.matrix_rank(a) == np.linalg.matrix_rank(a1) and np.linalg.matrix_rank(a) < n):
    print("The system of equations has infinitely many solutions")
else:
    print("The system of equations has a unique solution")
    print("The solution set of the system is: \n",np.linalg.inv(a).dot(b))

equation : 3
Hidden num: 2
-------Phương trình 1------
x[1][1] = 1
x[1][2] = -1
b[1] = 2
-------Phương trình 2------
x[2][1] = 1
x[2][2] = 3
b[2] = 2
-------Phương trình 3------
x[3][1] = 4
x[3][2] = 3
b[3] = 2
System of equations with no solution
