<a href="https://colab.research.google.com/github/Tranminhtuan48/pythonbasics/blob/main/Bosungtoanhoc_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [9]:
#1
v = np.array([1,2,3,4,5])

In [12]:
#2
w = np.array([1,2,3,4,5]).reshape(1,-1)

In [13]:
#3
v.ndim
w.ndim
v.shape
w.shape

(1, 5)

In [15]:
#4
u = np.array([1,2,3,4,5])
v = np.array([6,7,8,9,0])
np.column_stack((u,v))
np.hstack((u,v))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [41]:
#5
X = np.array([[[1,2,3,4,5], [6,7,8,9,2], [4,5,7,2,1]]])
X

array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 2],
        [4, 5, 7, 2, 1]]])

In [26]:
X.reshape(3,5)
X.ndim

3

In [34]:
t = np.dot(X,v)
t.ndim
t

array([[ 80, 230, 133]])

In [35]:
k = np.dot(X, np.transpose(w))
k.ndim
k

array([[[55],
        [90],
        [48]]])

In [39]:
np.transpose(X)

array([[[1],
        [6],
        [4]],

       [[2],
        [7],
        [5]],

       [[3],
        [8],
        [7]],

       [[4],
        [9],
        [2]],

       [[5],
        [2],
        [1]]])