<a href="https://colab.research.google.com/github/Tranminhtuan48/pythonbasics/blob/main/B%C3%A0i_t%E1%BA%ADp_v%E1%BB%81_nh%C3%A0_1_Chuong_1_M%C3%B4_t%E1%BA%A3_To%C3%A1n_h%E1%BB%8Dc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Cộng 2 vector (ndarray 1 chiều) trong Python

In [2]:
x = np.array([1,2,3,4])
y = np.array([5,3,2,1])
z = x + y
print(z)
print(z.ndim)
print(z.shape)

[6 5 5 5]
1
(4,)


Phép nhân đại lượng vô hướng với vector trong Python

In [3]:
x = np.array([1,2,3,4])
a = 15
z = a*x
print(z)
print(z.ndim)
print(z.shape)

[15 30 45 60]
1
(4,)


Tích vô hướng 2 vector (ndarray 1 chiều) trong Python

In [4]:
x = np.array([1,2,3,4])
y = np.array([5,3,2,1])
z = np.dot(x,y) #hoặc z = x.dot(y)
print(z)
print(z.ndim)
print(z.shape)

21
0
()


Tích hữu hướng (cross product) 2 vector trong Python

In [5]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.cross(x, y)
print(z)
print(z.ndim)
print(z.shape)

[-4  8 -4]
1
(3,)


Elementwise multiplication

In [6]:
x = np.array([1,2,3,4])
y = np.array([5,3,2,1])
z = x*y #hoặc z = np.multiply(x, y)
print(z)
print(z.ndim)
print(z.shape)

[5 6 6 4]
1
(4,)


Phép cộng 2 ma trận

In [7]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
Y = np.array([6,5,4,3,2,1]).reshape((2,3))
Z = X + Y
print(Z)
print(Z.ndim, '; ', Z.shape)

[[7 7 7]
 [7 7 7]]
2 ;  (2, 3)


Phép nhân ma trận với 1 đại lượng vô hướng

In [8]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
a = 2
Z = a*X
print(Z)
print(Z.ndim, '; ', Z.shape)

[[ 2  4  6]
 [ 8 10 12]]
2 ;  (2, 3)


Phép chuyển vị ma trận (transpose)

In [9]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
Z = X.T
print(Z)
print(Z.ndim, '; ', Z.shape)

[[1 4]
 [2 5]
 [3 6]]
2 ;  (3, 2)


Phép nhân 2 ma trận 

In [10]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
Y = np.array([6,5,4,3,2,1]).reshape((3,2))
Z = np.dot(X,Y)
print(Z)
print(Z.ndim, '; ', Z.shape)


[[20 14]
 [56 41]]
2 ;  (2, 2)


Phép nhân các phần tử có vị trí tương ứng 

In [11]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
Y = np.array([6,5,4,3,2,1]).reshape((2,3))
Z = np.multiply(X,Y) #hoặc Z = X*Y
print(Z)
print(Z.ndim, '; ', Z.shape)

[[ 6 10 12]
 [12 10  6]]
2 ;  (2, 3)


Tạo vector cột dạng ma trận đặc biệt 𝑅
𝑚×1

In [12]:
x = np.array([1,2,3,4,5]).reshape((5,1))
print(x)
print(x.ndim, '; ', x.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
2 ;  (5, 1)


Lấy ra 1 vector hàng từ ma trận X và chuyển thành ma trận đặc
biệt dạng 𝑅 1×n

In [13]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
m = X.shape[0]
n = X.shape[1]
print('m = ', m, '; n = ', n)
x = X[0, :]
print(x)
print(x.ndim, '; ', x.shape)
x = x.reshape((1,n))
print(x)
print(x.ndim, '; ', x.shape)


m =  2 ; n =  3
[1 2 3]
1 ;  (3,)
[[1 2 3]]
2 ;  (1, 3)


Lấy ra 1 vector hàng từ ma trận X và chuyển thành ma trận đặc
biệt dạng 𝑅 1×n

In [14]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
m = X.shape[0]
n = X.shape[1]
print('m = ', m, '; n = ', n)
x = X[:,1]
print(x)
print(x.ndim, '; ', x.shape)
x = x.reshape((m,1))
print(x)
print(x.ndim, '; ', x.shape)

m =  2 ; n =  3
[2 5]
1 ;  (2,)
[[2]
 [5]]
2 ;  (2, 1)


Xếp thêm 1 vector cột vào đầu ma trận: 𝑥 ∈ 𝑅
𝑚 ℎ𝑎𝑦 𝑥 ∈𝑅𝑚×1, 𝑋 ∈ 𝑅𝑚×𝑛,
                                                      𝑋 = [𝑥, 𝑋]

In [16]:
X =
np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape((4,3))
x = np.array([1,1,1,1]).reshape((4,1))
X = np.column_stack([x,X])
print(X)
print(X.ndim, '; ', X.shape)

SyntaxError: ignored

Tách 1 ma trận data ban đầu gồm n cột thành 1 ma trận con X
chứa các n-1 cột đầu tiên và 1 vector cột y lấy ra từ cột cuối cùng
của dat

In [15]:
data = np.array([[10,22,13,1],
 [9,6,5,0],
 [8,12,4,1],
 [6,5,7,0]])
X = data[:,:-1]
y = data[:,-1].reshape((data.shape[0], 1))
print(X)
print(X.ndim, '; ', X.shape)
print(y)
print(y.ndim, '; ', y.shape)


[[10 22 13]
 [ 9  6  5]
 [ 8 12  4]
 [ 6  5  7]]
2 ;  (4, 3)
[[1]
 [0]
 [1]
 [0]]
2 ;  (4, 1)


Tạo 1 tensor 𝑇 ∈ 𝑅 𝑚×𝑛×𝑘 với m = 2, n = 2 và k = 3, các giá trị được sinh ngẫu nhiên.

In [17]:
import numpy as np
m=2
n=2
k=3
T = np.random.randint(low=-5,
high=5,size=m*n*k).reshape(k,m,n)
print(T)


[[[ 2 -2]
  [-4  3]]

 [[-3  4]
  [ 1  3]]

 [[ 3 -2]
  [-2  1]]]


Tạo 1 tensor 𝑇2 ∈ 𝑅 𝑚×𝑛×𝑘×𝑞 chứa 2 tensor 𝑡1,𝑡2 ∈ 𝑅 𝑚×𝑛×𝑘 ,biết t1 và t2 được sinh ngẫu nhiên

In [18]:
import numpy as np
m=2
n=2
k=3
t1 = np.random.randint(low=-5,
high=5,size=m*n*k).reshape(k,m,n)
t2 = np.random.randint(low=-5,
high=5,size=m*n*k).reshape(k,m,n)
t3 = np.random.randint(low=-5,
high=5,size=m*n*k).reshape(k,m,n)
t4 = np.random.randint(low=-5,
high=5,size=m*n*k).reshape(k,m,n)
T = np.stack((t1, t2, t3, t4), axis=-1)
print(T.shape)
x = T[:,:,:,0]
print(x.shape)
m1 = x[0,:,:]
print(m1)
print(m1.shape)

(3, 2, 2, 4)
(3, 2, 2)
[[-1 -4]
 [-1 -2]]
(2, 2)
