<a href="https://colab.research.google.com/github/Tranminhtuan48/pythonbasics/blob/main/Sinh_mau_ngau_nhien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
import scipy.stats as st

Sử dụng thư viện Numpy

1. Sinh mẫu ngẫu nhiên bằng hàm arange trong khoảng [-15, 27] với khoảng cách là 0.7 và in kết quả ra màn hình

In [3]:
np.arange(-15, 27, 0.7)

array([-15. , -14.3, -13.6, -12.9, -12.2, -11.5, -10.8, -10.1,  -9.4,
        -8.7,  -8. ,  -7.3,  -6.6,  -5.9,  -5.2,  -4.5,  -3.8,  -3.1,
        -2.4,  -1.7,  -1. ,  -0.3,   0.4,   1.1,   1.8,   2.5,   3.2,
         3.9,   4.6,   5.3,   6. ,   6.7,   7.4,   8.1,   8.8,   9.5,
        10.2,  10.9,  11.6,  12.3,  13. ,  13.7,  14.4,  15.1,  15.8,
        16.5,  17.2,  17.9,  18.6,  19.3,  20. ,  20.7,  21.4,  22.1,
        22.8,  23.5,  24.2,  24.9,  25.6,  26.3,  27. ])

2. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 2.7 std = 1.2 và size = 40
In kết quả ra màn hình

In [4]:
np.random.normal(2.7, 1.2, 40)

array([ 1.7514109 ,  3.19240673,  3.14242325,  1.75079634,  3.41835875,
        5.11610903,  1.9765251 ,  3.07114714,  1.55374957,  2.94321838,
       -0.15083611,  2.60387028,  2.80134225,  2.00928957,  2.4662784 ,
        3.41395123,  2.12263255,  4.04106727,  2.77813635,  2.57037975,
        1.29839991,  1.75485259,  3.53071457,  3.597103  ,  2.02466225,
        2.09014535,  2.94087467,  3.16873175,  3.82452972,  2.58507665,
        1.78252704,  3.5198251 ,  4.95399472,  1.65200801,  4.00235832,
        1.87264748,  2.57195847,  2.69975913,  4.03187543,  1.25231174])

3. Sinh mẫu ngẫu nhiên từ vector ['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'] 
với kích thước là 17 theo phân phối chuẩn

In [5]:
np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 17)

array(['Viet Nam', 'Viet Nam', 'Viet Nam', 'Viet Nam', 'Britain',
       'Britain', 'Russia', 'Singapore', 'Russia', 'Britain', 'Britain',
       'France', 'France', 'Singapore', 'Viet Nam', 'Russia', 'Singapore'],
      dtype='<U9')

4. Sinh mẫu ngẫu nhiên ở câu 3 nhưng không theo phân phối chuẩn mà theo 1 vector đặc tả giá trị xác suất do bạn chọn

In [8]:
np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 17, p = [0.1, 0.2, 0.3, 0.2, 0.2])

array(['France', 'Singapore', 'France', 'Britain', 'Singapore', 'Britain',
       'Britain', 'Russia', 'France', 'Russia', 'Russia', 'Viet Nam',
       'Singapore', 'Viet Nam', 'Britain', 'Britain', 'Britain'],
      dtype='<U9')

Sử dụng thư việc scipy.stats để sinh mẫu ngẫu nhiên

1. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 12.7, std = 2.6 và size = 30. In kết quả ra màn hình

In [10]:
st.norm.rvs(loc = 12.7, scale = 2.6, size = 30)

array([12.96020511, 15.13164806, 14.04983385, 10.91792069, 11.13384511,
        5.61373666, 15.44031114, 14.47476765, 10.99671438, 15.13444479,
       11.98325636, 14.2603666 , 11.20266242, 15.89978015,  9.5371045 ,
       13.78883782, 15.97825428, 13.16995946,  7.98220152, 16.74804742,
       12.53774076, 15.11964639,  7.87488832, 11.41684999, 13.84584931,
       12.76849365, 13.4180661 , 15.78143744,  5.08438585, 13.89671809])

2. Hãy sinh một mẫu ngẫu nhiên theo phân phối Poisson

In [13]:
st.poisson.rvs(loc=-15, mu=10, size=50)

array([ -3,  -3,  -7,  -1,  -9,  -3, -11, -11,  -4,  -7,  -7,  -8,  -2,
        -5,  -3,  -2,   3,  -6,  -9,  -6,  -4,  -8,  -7,  -6,  -5,  -2,
        -7,  -5,  -1,  -8,  -6,  -3,  -3,  -3,  -3,  -5,  -4, -10,  -8,
       -12, -10,  -5,   2,  -3,  -1,  -8,  -5,  -7,  -1,  -4])